version: '3'

services:
    gomdb:
      container_name: gomdb
      image: mongo:latest
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
      ports:
        - "27017:27017"
      volumes:
        - gomdb:/data/db
volumes:
    mdbdata: